site_name: Understanding Computing-Clusters
nav:
  - Introduction: index.md
  - Nodes and Jobs: 01_nodes_and_jobs.md

theme: 
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js